name: "Build Maven"
description: "Builds a maven project"
inputs:
  java-version:
    default: 21
    description: "Version of Java to build with"
  java-distribution:
    default: "temurin"
    description: "Distribution of Java to use"
  token:
    required: true
    description: "PAT to use to authenticate with github"
outputs:
  jar-path:
    description: "path of the built jar file"
    value: ${{ steps.build-step.outputs.jar-path }}
runs:
  using: "composite"
  steps:
    - name: Set up JDK ${{ inputs.java-version }}
      uses: actions/setup-java@v4.2.1
      with:
        java-version: ${{ inputs.java-version }}
        distribution: temurin

    - name: Configure Maven settings
      run: |
        mkdir -p ~/.m2
        echo "<settings><servers><server><id>github</id><username>strenkml</username><password>${{ inputs.token }}</password></server></servers></settings>" > ~/.m2/settings.xml
      shell: bash

    - name: Build with Maven
      id: build-step
      run: |
        mvn clean package
        echo "jar-path=$(find ./target -iname '*.jar' ! -iname '*-dev*' ! -iname 'original-*')" >> $GITHUB_OUTPUT
      shell: bash
